{{- range $name, $cfg := .Values.components }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-web-app.fullname" (dict "nameOverride" $cfg.nameOverride "ctx" $) }}-{{ $name }}
  labels:
    {{- include "my-web-app.labels" (dict "name" $name "ctx" $) | nindent 4 }}
spec:
  replicas: {{ $cfg.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-web-app.selectorLabels" (dict "name" $name "ctx" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-web-app.labels" (dict "name" $name "ctx" $) | nindent 8 }}
        {{- with $cfg.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $cfg.image.repository }}:{{ $cfg.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $cfg.image.pullPolicy }}
          {{- with $cfg.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $cfg.service.port }}
              protocol: TCP
          {{- with $cfg.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $cfg.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $cfg.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $cfg.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $cfg.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
