{{- range $name, $cfg := .Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-web-app.fullname" (dict "nameOverride" $cfg.nameOverride "ctx" $) }}-{{ $name }}-service
  labels:
    {{- include "my-web-app.labels" (dict "name" $name "ctx" $) | nindent 4 }}
spec:
  type: {{ $cfg.service.type }}
  ports:
    - port: {{ $cfg.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-web-app.selectorLabels" (dict "name" $name "ctx" $) | nindent 4 }}
{{- end }}